### ISSUE TITLE
Possible scaling issue with QueueContainer<V>

### ISSUE THREAD

**Issue by ricea** [stardazed/sd-streams#1]
If `QueueContainer<V>.[queue_]` is compiled to a JS array, then it's likely to become slow when the queue is very large.

See https://bugs.chromium.org/p/chromium/issues/detail?id=681493 for background information about when the same issue happened in Chrome.

**Comment by zenmumbler** [comment]
Hi @ricea, sorry I didn't notice this earlier, different GH account. I incorporated the test into the polyfill package (this repo is also now a monorepo) and tried it out. The issue is only present in Chrome; Safari and Firefox scale linearly with queue size. Nevertheless, it's a real issue and I'm not one to shy away from adding new containers to my code ;) I will add my Deque container (simplified to be just a queue) to the implementation soon and also incorporate the latest changes I saw in the streams commit updates.

Below are timings for the test on my 2010 iMac.
![wkffcr](https://user-images.githubusercontent.com/329445/42787723-107d59f8-895c-11e8-9799-58a4bcb130e5.png)

**Comment by zenmumbler** [comment]
By replacing the arrays with a basic queue the problem goes away in Chrome. It's hard to really measure the effect of this change in Safari and Firefox as they spend a lot of time in internal promise code handling. Perhaps worth filing an issue with them.

Fun detail, Chrome using the SD polyfill is a bit faster than the internal implementation on this test. The timings vary, again due to the many, many promises, but every time SD comes out on top 😄

![chrome](https://user-images.githubusercontent.com/329445/42848182-bdac85c8-8a1e-11e8-8397-589a2fa31b1a.png)
